### PR TITLE
converted fetch requests to useSWR hooks

### PR DESCRIPTION
**Pull request by brownboycodes**
responding to issue #32 **Convert fetch api calls to SWR** 
<br>

In this pull request, I have :
1.  created a new branch **implement-swr** 
2.  added SWR as a dependency 📦 
3.  have converted the fetch requests into implementations of useSWR hooks in */components/formwrapper.js* 🏗️ 🔨 ✨ 
4.  added comments to understand which parts of the code has been replaced 💡 

<br>
I would be happy if I have been of any help and would appreciate your feedback

### CODE REVIEW

**Comment by RizkyRajitha** [comment]
hi @brownboycodes ,

good work, thanks for your valuable contribution . 
can you please make the pr to the `dev` branch , instead of the `master branch`.

**Review by RizkyRajitha — CHANGES_REQUESTED** [review]
can you please make the pr to the dev branch , instead of the master branch.

**Comment by brownboycodes** [comment]
> can you please make the pr to the dev branch , instead of the master branch.

yes Sir I will, and sorry didn't know that

**Comment by brownboycodes** [comment]
> hi @brownboycodes ,
> 
> good work, thanks for your valuable contribution .
> can you please make the pr to the `dev` branch , instead of the `master branch`.

Made the changes in a **new pull request** as I was _unable to change the base in the current pull request_.  
Please have a look.

**Comment by RizkyRajitha** [comment]
> > can you please make the pr to the dev branch , instead of the master branch.
> 
> yes Sir I will, and sorry didn't know that

@brownboycodes that actually my fault since i haven't  wrote the contribution guidelines. now i have added the contribution guidelines , code of conduct and also the pr template . 

good work @brownboycodes .

**Pull request closed without merging**
