### PR TITLE
converted fetch requests to useSWR hooks & changed pull request to dev branch

### PR DESCRIPTION
**Pull request by brownboycodes**
responding to issue #32 **Convert fetch api calls to SWR** 
<br>

In this pull request, I have :
1.  created a new branch **implement-swr** 
2.  added SWR as a dependency 📦 
3.  have converted the fetch requests into implementations of useSWR hooks in */components/formwrapper.js* 🏗️ 🔨 ✨ 
4.  added comments to understand which parts of the code has been replaced 💡 

<br>
I would be happy if I have been of any help and would appreciate your feedback

### CODE REVIEW

**Comment by RizkyRajitha** [comment]
@brownboycodes thanks for your valuable contribution 👌 .

**Comment by brownboycodes** [comment]
@RizkyRajitha can I mention my contributions to LinkIn Demo on my Resume & LinkedIn (as contribution to Open Source Projects)?

**Comment by RizkyRajitha** [comment]
@brownboycodes yup ,no problem . 
this is actually Linkin, not linkin demo 🙄.

**Comment by RizkyRajitha** [comment]
@brownboycodes sorry,  i think you got the emoji wrong , i am not offended in anyway why would i , you just made a valuable contribution to this project , and i appreciate that very much  .
i just corrected you , because there is a demo version too https://github.com/RizkyRajitha/linkindemo , and this is not that one . 
excited to see more contributions from you ✌.

**Pull request merged**
